version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
        -   POSTGRES_HOST_AUTH_METHOD=trust
        -   POSTGRES_USER=test
        -   POSTGRES_PASSWORD=password
        -   POSTGRES_HOST=postgres
        -   POSTGRES_PORT=5432
        -   POSTGRES_DB=example
        ports: 
            - '5432:5432'
        volumes:
            - /var/lib/postgresql/data
    nginx-proxy:
        depends_on:
        - api
        - client
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./nginx
        ports:
        - '3090:100'
    api:
        depends_on: 
            - postgres
        build:
            dockerfile: Dockerfile
            context: ./backend
        environment: 
            -   POSTGRES_USER=test
            -   POSTGRES_PASSWORD=password
            -   POSTGRES_HOST=postgres
            -   POSTGRES_PORT=5432
            -   POSTGRES_DB=example
        
    client:
        depends_on:
            - postgres
        stdin_open: true
        build:
            dockerfile: Dockerfile
            context: ./frontend
    
        

            