version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
           - POSTGRES_PASSWORD=postgres_password
        ports: 
            - '5432:5432'
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '3050:80'
    api:
        depends_on: 
            - postgres
        build:
            dockerfile: Dockerfile
            context: ./backend
        environment: 
            - DATABASE_USER=shehryarbajwa
            - DATABASE_TYPE=postgres
            - DATABASE_NAME=trivia
            - DATABASE_PASSWORD=postgres_password
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile
            context: ./frontend
        

            